// <auto-generated />
namespace Reportes.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class ADDTABLESPERMISOS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ADDTABLESPERMISOS));
        
        string IMigrationMetadata.Id
        {
            get { return "201706291656393_ADD-TABLES-PERMISOS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
